name: Android Build and Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip')"
    runs-on: ubuntu-latest
    steps:
      # Step 1: Get the code from repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Setup Java
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Make gradlew executable
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # Step 4: Build the project
      - name: Build project
        run: ./gradlew assembleDebug

      - name: Debug info
        run: echo " The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - name: List files
        run: |
          ls ${{ github.workspace }} 

  test:
    runs-on: ubuntu-latest
    needs: build  # This job depends on build job
    steps:
      # Step 1: Get the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Setup Java
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Make gradlew executable
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # Step 4: Run unit tests (tests that don't need device)
      - name: Run unit tests
        run: ./gradlew testDebugUnitTest

      # Step 5: Run UI tests (will fail without device, but shows structure)
      - name: Run UI tests
        run: ./gradlew connectedDebugAndroidTest